image: docker.oxygene.sk/acoustid/chromaprint-build

stages:
  - test
  - package

test:
  stage: test
  script:
    - mkdir build.test
    - cd build.test
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_TOOLS=ON ..
    - make
    - make check

.package: &package
  stage: package
  script:
    - JOB_NAME=($CI_BUILD_NAME)
    - export OS=${JOB_NAME[1]}
    - export ARCH=${JOB_NAME[2]}
    - ./package/build.sh
  artifacts:
    paths:
      - chromaprint-*-*

package linux i686: *package
package linux x86_64: *package
package windows i686: *package
package windows x86_64: *package
