image: docker.oxygene.sk/acoustid/chromaprint-build

stages:
  - test
  - package

.test: &test
  stage: test
  script:
    - JOB_NAME=($CI_BUILD_NAME)
    - mkdir build.test.${JOB_NAME[1]}
    - cd build.test.${JOB_NAME[1]}
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_TOOLS=ON $EXTRA_CMAKE_ARGS ..
    - make
    - make check

test avfft:
  <<: *test
  variables:
    EXTRA_CMAKE_ARGS: -DWITH_AVFFT=ON

test fftw3:
  <<: *test
  variables:
    EXTRA_CMAKE_ARGS: -DWITH_FFTW3=ON

test fftw3f:
  <<: *test
  variables:
    EXTRA_CMAKE_ARGS: -DWITH_FFTW3F=ON

test kissfft:
  stage: test
  script:
    - mkdir build.test.kissfft
    - cd build.test.kissfft
    - git clone https://code.oxygene.sk/acoustid/kissfft.git
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_TOOLS=ON -DWITH_KISSFFT=ON -DKISSFFT_SOURCE_DIR=$(pwd)/kissfft ..
    - make
    - make check

.package: &package
  stage: package
  script:
    - JOB_NAME=($CI_BUILD_NAME)
    - export OS=${JOB_NAME[1]}
    - export ARCH=${JOB_NAME[2]}
    - ./package/build.sh
  artifacts:
    paths:
      - chromaprint-*-*
    expire_in: 7d

.package-macos: &package-macos
  <<: *package
  tags:
    - osx

package linux i686: *package
package linux x86_64: *package
package windows i686: *package
package windows x86_64: *package
package macos i386: *package-macos
package macos x86_64: *package-macos
