image: docker.oxygene.sk/acoustid/chromaprint-build

stages:
  - test
  - package

#test:
#  stage: test
#  script:
#    - mkdir build.test
#    - cd build.test
#    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_TOOLS=ON ..
#    - make
#    - make check

package:linux-i686:
  stage: package
  script:
    - mkdir build.linux-i686
    - cd build.linux-i686
    - wget -O artifacts.zip 'https://code.oxygene.sk/acoustid/ffmpeg-build/builds/artifacts/master/download?job=build%3Alinux-i686'
    - mkdir ffmpeg
    - unzip ../artifacts.zip
    - cd ..
    - rm artifacts.zip
    - CC='gcc -m32' cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_TOOLS=ON -DBUILD_SHARED_LIBS=OFF -DFFMPEG_ROOT=`pwd`/ffmpeg ..
