sudo: no
addons:
  apt:
    packages:
      - libavcodec-dev
      - libavformat-dev
      - libgtest-dev

language: cpp
compiler:
  - gcc
  - clang

script:
  - cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug .
  - make
  - make check
